-- CREATION OF THE PREDICTION MODEL
CREATE MODEL "StayModel" PREDICTING (Stay) FROM MLTEST_Data.EpisodeTrain

-- VALIDATION OF THE MODEL WITH THE PRE-LOADED EPISODES
VALIDATE MODEL "StayModel" FROM MLTEST_Data.Episode

-- MODEL IS TRAINED WITH THE CSV DATA PRE-LOADED
TRAIN MODEL StayModel
USING {
    "seed": 3,
    "verbosity": 1,
    "TrainMode": "BALANCE"
    };

-- GET STAY PREDICTION WITH THE LAST EPISODE PERSISTED
SELECT ID, PREDICT("StayModel") AS PredictedStay
FROM MLTEST_Data.Episode WHERE %ID = ?

SELECT ID, PREDICT("StayModel") AS PredictedStay
FROM mltest_data.episode
ORDER BY ID DESC
FETCH FIRST 50 ROWS ONLY;

-- OTRO Modelo

-- 5) Métricas y runs registrados
SELECT * FROM INFORMATION_SCHEMA.ML_MODELS WHERE MODEL_NAME='StayModel';
SELECT * FROM INFORMATION_SCHEMA.ML_TRAINED_MODELS WHERE MODEL_NAME='StayModel';
SELECT * FROM INFORMATION_SCHEMA.ML_TRAINING_RUNS WHERE MODEL_NAME='StayModel';
SELECT * FROM INFORMATION_SCHEMA.ML_VALIDATION_RUNS WHERE MODEL_NAME='StayModel';
SELECT * FROM INFORMATION_SCHEMA.ML_VALIDATION_METRICS WHERE MODEL_NAME='StayModel';


-- Numeros de métricas específicas
SELECT
  MODEL_NAME,
  TRAINED_MODEL_NAME,
  VALIDATION_RUN_NAME,
  METRIC_NAME,
  METRIC_VALUE
FROM INFORMATION_SCHEMA.ML_VALIDATION_METRICS
WHERE MODEL_NAME = 'StayModel'
  AND TRAINED_MODEL_NAME = 'StayModel_t6'
  AND METRIC_NAME IN (
    'Micro-averaged Precision',
    'Micro-averaged Recall',
    'Micro-averaged F-Measure',
    'Micro-averaged ROC-AUC',
    'Accuracy'
  );

-- CREATION OF THE PREDICTION MODEL
CREATE MODEL "StayModel2" PREDICTING (Stay) FROM MLTEST_Data.EpisodeTrain

-- MODEL IS TRAINED WITH THE CSV DATA PRE-LOADED
TRAIN MODEL "StayModel2" 
USING {"verbosity": 1, "TrainMode": "BALANCE"}

-- VALIDATION OF THE MODEL WITH THE PRE-LOADED EPISODES
VALIDATE MODEL "StayModel2" FROM MLTEST_Data.Episode  

-- Numeros de métricas específicas
SELECT
  MODEL_NAME,
  TRAINED_MODEL_NAME,
  VALIDATION_RUN_NAME,
  METRIC_NAME,
  METRIC_VALUE
FROM INFORMATION_SCHEMA.ML_VALIDATION_METRICS
WHERE MODEL_NAME = 'StayModel2'
  AND TRAINED_MODEL_NAME = 'StayModel2_t1'
  AND METRIC_NAME IN (
    'Micro-averaged Precision',
    'Micro-averaged Recall',
    'Micro-averaged F-Measure',
    'Micro-averaged ROC-AUC',
    'Accuracy'
  );

-- GET STAY PREDICTION WITH THE LAST EPISODE PERSISTED
SELECT PREDICT("StayModel2") AS PredictedStay FROM MLTEST_Data.Episode WHERE %ID = ?

-- 5) Métricas y runs registrados
SELECT * FROM INFORMATION_SCHEMA.ML_MODELS WHERE MODEL_NAME='StayModel2';
SELECT * FROM INFORMATION_SCHEMA.ML_TRAINED_MODELS WHERE MODEL_NAME='StayModel2';
SELECT * FROM INFORMATION_SCHEMA.ML_TRAINING_RUNS WHERE MODEL_NAME='StayModel2';
SELECT * FROM INFORMATION_SCHEMA.ML_VALIDATION_RUNS WHERE MODEL_NAME='StayModel2';
SELECT * FROM INFORMATION_SCHEMA.ML_VALIDATION_METRICS WHERE MODEL_NAME='StayModel2';